language: java
jdk:
  - openjdk8
addons:
  sonarcloud:
    organization: vladislavsevruk
    token:
      secure: tQTop7uEy76HC7vHDZsGrSae1fQK/AUrQohOS+3B4HRgIF6cFsSDQxmTSa0u3zw+r4fBLA25GPVj+9y7t0rgJHBdhqVRwwbLjU9m0/171k7BwfEqZOL4cXZP7QkinmsJfc9tc70/KcRsppVTIo5gIn2ehPPC04WtQGQ+ALSm+XGT6u5AP0o3L9UELYFBPBIl3NunGFslT6e0sRPuMh4peiWG3epmziE3tyVh936hLGbOXyZQ/49LDVyNqM/adjmt+DI7RTAdv7maiMsCbbc6sFNkaOI6Nt6tlsUWTkz6PCnl8drgqu+ryRmfXjs6fIrM7gXCySiXjPH08i1DVQeloDOlHjqIYJwnc6cE0cQ+9fQjVCSMIApnK7WCgXJdr1rjc33XBx8TFZh/IN+7ZT6LQ9IhR6lPLW42SYMCuidmowqWLkK6x8q7QZsx/8I34OaTvVYzjy9AcUQG3t2JDc1hOVoDnbFJnuYN8IhI3xAYBmpSoi1NT6KJjs09F+M5nSVLcIy2F3RVmq2HeS9O40XEet1RYD/Drqxjm5WFEB3YzdsYmZ2fWIofPYMbclurXK5z7XLT7R6KBm3xTYA6qBG2OWMNI4KgUGsBaQ5TZVyyfqOiZczu4DNx/nlQaZRwFRZ4deMQ7K9xJjiRsdOvk7oDAURuUhq4HFi7Jonc2FHLj+Y=
before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/
cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/
script:
  - ./gradlew clean jacocoTestReport sonarqube
  - ./gradlew build --scan -s